ТЗ 12 спринта
ttasyan/filmorate pull request #3
Opened 2024-11-23 17:04 UTC by ttasyan

2024-12-05 06:37 UTC, slavrikk reviewed
Так же следует поправить билд, приложение не стартует:

Run /tmp/wait-for-it.sh -t 60 localhost:8080
wait-for-it.sh: waiting 60 seconds for localhost:[8](https://github.com/ttasyan/filmorate/actions/runs/12071289214/job/33662753284?pr=3#step:10:9)080
wait-for-it.sh: timeout occurred after waiting 60 seconds for localhost:8080
Error: Process completed with exit code 124.

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmLikeRepository.java
> +    private static final String ADD_QUERY = "INSERT INTO likes (film_id, user_id) VALUES (?, ?)";
Переменные пишутся перед конструктором

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    private static final String FIND_ALL_QUERY = "SELECT * FROM films";
Переменные пишутся перед конструктором

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        Integer genreMaxId = jdbc.queryForObject("SELECT COUNT(*) FROM mpa", Integer.class);
Выполняется запрос для всех mpa, хотя передаются жанры `List<Genre> genres`

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    private static final String FIND_ALL_QUERY = "SELECT * FROM films";
Замечание для всего кода

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> allFilms = new ArrayList<>(filmStorage.getFilms().values().stream()
Популярные фильмы так же следует найти с помощью sql запроса

2024-12-05 06:37 UTC, slavrikk commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        friends1.retainAll(friends2);
Общих друзей следует найти с помощью sql запроса

2024-12-05 06:37 UTC, slavrikk commented on src/main/resources/schema.sql
> +
Так же следует создать таблицу для mpa

2024-12-05 06:37 UTC, slavrikk commented on src/main/resources/data.sql
Следует добавить жанры и рейтинги

2024-12-23 05:26 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<FilmDto> popularFilms(@RequestParam(required = false, defaultValue = "10") Integer count) {
Когда устанавливаем defaultValue, то required = false указывать избыточно, оно подразумевается по умолчанию

2024-12-23 05:27 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmDto getWithGenre(@PathVariable Integer id) {
Можно использовать примитивный тип int

2024-12-23 05:28 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +public class BaseRepository<T> {
Отлично, что вынесли общий код в базовый класс

2024-12-23 05:34 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +
Нужно еще добавить обновление жанров фильма

2024-12-23 05:35 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        return film;
Нужно добавить сохраниние жанров

2024-12-23 05:36 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
InMemory реализации не нужны уже, нужно удалить из проекта

2024-12-23 05:45 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final FilmStorage filmStorage;
Стораджи нужно убрать, используем только хранение в БД

2024-12-23 05:52 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        setGenres(film);
Нужно добавить сохранение жанров для фильма (всавка в таблицу FILM_GENRES)

2024-12-23 05:56 UTC, VadimZharkov requested changes
Нужно доработать, основная ошибка, то что одновременно для хранения сущностей используется и реализация хранения в памяти и в БД. Нужно оставить только хранение в БД,

2024-12-25 12:23 UTC, VadimZharkov approved these changes

2024-12-25 12:28 UTC, merged